Repository octobercms/docs, pull requests merged in 2018-12, with the labels that each got.

#337 Added MorphOne Documentation
  database-relations.md
Labels: Type: Enhancement

#342 Add "parentKey" and "relatedKey" options
  database-relations.md
Labels: Type: Maintenance

#341 add section for page tag
  config/toc-markup.yaml
  markup-tag-page.md
Labels: Type: Maintenance

#344 Add format description of the backend lists text column type
  backend-lists.md
Labels: Status: Completed, Type: Maintenance

#343 nestedform documentation.
  backend-forms.md
Labels: Status: Review Needed, Type: Maintenance

#345 removed unnecessary line
  backend-widgets.md
Labels: Type: Maintenance

#346 Clarify implementation of custom validation rules in plugins
  services-validation.md
Labels: Status: Completed, Type: Enhancement
