Repository octobercms/docs, pull requests merged in 2019-02, with the labels that each got.

#355 Small typo
  cms-partials.md
Labels: Type: Maintenance

#358 Update setup-configuration.md
  setup-configuration.md
Labels: Type: Maintenance

#357 Docs update for OctoberCMS #4083
  ajax-introduction.md
  plugin-updates.md
Labels: Status: Review Needed, Type: Maintenance

#356 Document CLI List, Disable and Enable Plugin.
  console-commands.md
Labels: Status: Completed, Type: Maintenance
