Repository octobercms/docs, pull requests merged in 2019-03, with the labels that each got.

#362 Sluggable suffix starts at -2
  database-traits.md
Labels: Type: Maintenance

#365 Add documentation for controller middleware
  backend-controllers-ajax.md
  plugin-registration.md
Labels: Status: Blocked, Type: Maintenance

#367 Add headCssClass column option documentation
  backend-lists.md
Labels: Status: Completed, Type: Maintenance

#366 Added allowTrashedSlugs section
  database-traits.md
Labels: Status: Blocked, Status: Review Needed
