Repository octobercms/docs, pull requests merged in 2019-07, with the labels that each got.

#382 Update plugin-registration.md
  plugin-registration.md
Labels: Type: Maintenance

#383 Added directory structure example for Form Widgets
  backend-widgets.md
Labels: Status: Completed, Type: Maintenance

#380 CMS/Pages Readability Improvements
  cms-pages.md
Labels: Status: Completed, Type: Maintenance

#385 Add description for ignoreTimezone
  backend-forms.md
Labels: Status: Completed, Type: Maintenance

#386 Remove outdated whereLoose and add new whereStrict
  services-collections.md
Labels: Status: Response Needed, Type: Maintenance

#370 Option for disable global ajax events
  ajax-attributes-api.md
Labels: Status: Completed, Type: Maintenance

#352 Add description for backend form widget option "maxFilesize"
  backend-forms.md
Labels: Status: Completed, Type: Maintenance

#391 Add documentation for Data Table widget
  backend-forms.md
Labels: Status: Completed, Type: Maintenance
